language: swift
osx_image: xcode9.2
xcode_project: StellarKit.xcodeproj
xcode_scheme: StellarKit
xcode_sdk: iphonesimulator8.4

before_script:
  - git clone https://github.com/kinfoundation/travis-stellar-core-macos.git
  - cd travis-stellar-core-macos && ./setup.sh && cd ..

script:
  - xcodebuild test -scheme StellarKit -destination 'platform=iOS Simulator,name=iPhone 8 Plus'
